global using BuildingBlocks;
global using BuildingBlocks.Behaviors;
global using BuildingBlocks.CQRS;
global using Carter;
global using FluentValidation;
global using Mapster;
global using MediatR;
global using ShoppingCart.API.Models;
global using System.Reflection;